apiVersion: v1
kind: Service
metadata:
  name: jpetstore-service
spec:
  selector:
    app.kubernetes.io/app: jpetstore
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080